In [2]:
import pandas as pd

In [3]:
pd.__version__

'2.3.2'

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [5]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [6]:
df.nunique()

engine_displacement      36
num_cylinders            14
horsepower              192
vehicle_weight         9704
acceleration            162
model_year               24
origin                    3
fuel_type                 2
drivetrain                2
num_doors                 9
fuel_efficiency_mpg    9704
dtype: int64

In [7]:
df.isnull()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                   False          False       False           False   
1                   False          False       False           False   
2                   False           True       False           False   
3                   False          False        True           False   
4                   False          False       False           False   
...                   ...            ...         ...             ...   
9699                False          False       False           False   
9700                False           True       False           False   
9701                False          False       False           False   
9702                False          False       False           False   
9703                False          False       False           False   

      acceleration  model_year  origin  fuel_type  drivetrain  num_doors  \
0            False       False   False      False       False      False   
1            False       False   False      False       False      False   
2            False       False   False      False       False      False   
3            False       False   False      False       False      False   
4            False       False   False      False       False      False   
...            ...         ...     ...        ...         ...        ...   
9699         False       False   False      False       False       True   
9700         False       False   False      False       False      False   
9701         False       False   False      False       False      False   
9702         False       False   False      False       False      False   
9703         False       False   False      False       False      False   

      fuel_efficiency_mpg  
0                   False  
1                   False  
2                   False  
3                   False  
4                   False  
...                   ...  
9699                False  
9700                False  
9701                False  
9702                False  
9703                False  

[9704 rows x 11 columns]

In [8]:
df.isnull().any()

engine_displacement    False
num_cylinders           True
horsepower              True
vehicle_weight         False
acceleration            True
model_year             False
origin                 False
fuel_type              False
drivetrain             False
num_doors               True
fuel_efficiency_mpg    False
dtype: bool

In [9]:
df[df['origin'] == 'Asia']

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0         NaN     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

In [10]:
df[df['origin'] == 'Asia'].fuel_efficiency_mpg

8       16.823554
12      16.175820
14      11.871091
20      18.889083
21      16.077730
          ...    
9688    11.054830
9692    11.711653
9693    17.202782
9698    13.933716
9703    14.884467
Name: fuel_efficiency_mpg, Length: 3247, dtype: float64

In [11]:
df[df['origin'] == 'Asia'].fuel_efficiency_mpg.max()

23.759122836520497

In [12]:
df.horsepower.median()

149.0

In [13]:
df.horsepower.mode()

0    152.0
Name: horsepower, dtype: float64

In [14]:
df.horsepower = df.horsepower.fillna(152.0)

In [15]:
df.horsepower.median()

152.0

In [16]:
df[df['origin' == 'Asia']]

KeyError: False

In [17]:
df[df['origin'] == 'Asia']

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0       152.0     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

In [24]:
df.loc[df['origin'] == 'Asia',['vehicle_weight','model_year']].head(7).values

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [25]:
X = df.loc[df['origin'] == 'Asia',['vehicle_weight','model_year']].head(7).values

In [26]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [27]:
X.T

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [28]:
XTX = X.T

In [29]:
XTX

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [30]:
XTX.iloc[::-1]

AttributeError: 'numpy.ndarray' object has no attribute 'iloc'

In [31]:
XTX[::-1]

array([[2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ],
       [2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819]])

In [32]:
data = [1100, 1300, 800, 900, 1000, 1100, 1200]

In [33]:
y = pd.array(data)

In [34]:
y

<IntegerArray>
[1100, 1300, 800, 900, 1000, 1100, 1200]
Length: 7, dtype: Int64

In [35]:
import numpy as np


In [37]:
np.dot(XTX[::-1],XTX)

ValueError: shapes (2,7) and (2,7) not aligned: 7 (dim 1) != 2 (dim 0)

In [38]:
XTX


array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [39]:
np.linalg.inv(XTX)

LinAlgError: Last 2 dimensions of the array must be square

In [40]:
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [41]:
X.T

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [42]:
XTX

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [43]:
XTX = np.dot(X,X.T)

In [44]:
XTX

array([[11431242.46085133, 11608190.92541486, 13770311.23387465,
        10111792.75336224, 11282536.19632532, 11780081.29349753,
        14281180.86123177],
       [11608190.92541486, 11790026.46575708, 14007802.20739725,
        10255171.44187306, 11455668.70489329, 11966096.78727446,
        14531088.48421337],
       [13770311.23387465, 14007802.20739725, 16863697.77478558,
        12031947.83608462, 13574023.463935  , 14232076.05656009,
        17530181.51805091],
       [10111792.75336224, 10255171.44187306, 12031947.83608462,
         9025088.58092514,  9989516.7638366 , 10397924.16669749,
        12456257.9230991 ],
       [11282536.19632532, 11455668.70489329, 13574023.463935  ,
         9989516.7638366 , 11136831.64128077, 11624252.15672766,
        14075069.26273247],
       [11780081.29349753, 11966096.78727446, 14232076.05656009,
        10397924.16669749, 11624252.15672766, 12145826.2645139 ,
        14766233.02574041],
       [14281180.86123177, 14531088.48421337, 175301

In [45]:
np.linalg.inv(XTX)

array([[ 3.19409743e+08, -3.45971801e+07, -2.78324217e+08,
        -7.78241981e+07,  1.67379982e+07, -1.72136419e+08,
         2.24690639e+08],
       [ 2.57200169e+08,  8.20389195e+08, -1.13765246e+08,
        -1.69634178e+08, -4.41130505e+08, -3.27953379e+08,
        -2.38828329e+07],
       [-3.90723642e+08, -2.16060684e+08,  1.34235309e+08,
         3.24009117e+08,  7.45998855e+07,  2.31725421e+07,
         5.14736846e+07],
       [-3.31264254e+08, -2.14510114e+08,  3.86914074e+08,
         2.84922793e+08,  1.32418220e+08, -9.49560850e+07,
        -1.61582860e+08],
       [ 1.80453141e+08, -2.20054218e+08, -1.83259500e+08,
        -3.00070277e+07, -2.40526282e+08,  3.98003878e+08,
         9.40973588e+07],
       [-2.36464343e+08, -1.67629002e+08, -7.57998715e+06,
        -2.26195328e+08,  5.04299633e+08,  2.18313030e+08,
        -8.54939349e+07],
       [ 1.99057968e+08,  3.31913714e+07,  6.28987345e+07,
        -1.03693014e+08, -4.64809203e+07, -4.52677339e+07,
        -9.9480870

In [46]:
np.dot(np.linalg.inv(XTX),X.T)

ValueError: shapes (7,7) and (2,7) not aligned: 7 (dim 1) != 2 (dim 0)

In [47]:
X.T

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [48]:
np.linalg.inv(XTX)

array([[ 3.19409743e+08, -3.45971801e+07, -2.78324217e+08,
        -7.78241981e+07,  1.67379982e+07, -1.72136419e+08,
         2.24690639e+08],
       [ 2.57200169e+08,  8.20389195e+08, -1.13765246e+08,
        -1.69634178e+08, -4.41130505e+08, -3.27953379e+08,
        -2.38828329e+07],
       [-3.90723642e+08, -2.16060684e+08,  1.34235309e+08,
         3.24009117e+08,  7.45998855e+07,  2.31725421e+07,
         5.14736846e+07],
       [-3.31264254e+08, -2.14510114e+08,  3.86914074e+08,
         2.84922793e+08,  1.32418220e+08, -9.49560850e+07,
        -1.61582860e+08],
       [ 1.80453141e+08, -2.20054218e+08, -1.83259500e+08,
        -3.00070277e+07, -2.40526282e+08,  3.98003878e+08,
         9.40973588e+07],
       [-2.36464343e+08, -1.67629002e+08, -7.57998715e+06,
        -2.26195328e+08,  5.04299633e+08,  2.18313030e+08,
        -8.54939349e+07],
       [ 1.99057968e+08,  3.31913714e+07,  6.28987345e+07,
        -1.03693014e+08, -4.64809203e+07, -4.52677339e+07,
        -9.9480870

In [49]:
X.T

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [50]:
np.dot(X.T,np.linalg.inv(XTX))

array([[ 2.44140625e-04,  6.71386719e-04,  1.83105469e-04,
        -7.93457031e-04, -3.35693359e-04, -4.88281250e-04,
         4.27246094e-04],
       [ 6.10351562e-05, -1.36566162e-03, -3.50952148e-04,
         1.49536133e-03,  4.57763672e-04,  8.39233398e-04,
        -3.66210938e-04]])

In [51]:
np.dot(np.dot(X.T,np.linalg.inv(XTX)),y)

array([0.21362305, 0.29830933])

In [52]:
w = np.dot(np.dot(X.T,np.linalg.inv(XTX)),y)

In [53]:
w

array([0.21362305, 0.29830933])

In [54]:
np.sum(w)

np.float64(0.511932373046875)